INSERT INTO yaku (en_name, ja_name) VALUES
('Aka Dora', '赤ドラ'),
('Chankan', '槍槓'),
('Chantai', '混全帯幺九'),
('Chiitoitsu', '七対子'),
('Chinitsu', '清一色'),
('Yakuhai (chun)', '役牌（中）'),
('Double Open Riichi', 'ダブル立直'),
('Double Riichi', 'ダブル立直'),
('Dora', 'ドラ'),
('Yakuhai (east)', '役牌（東）'),
('Haitei Raoyue', '海底摸月'),
('Yakuhai (haku)', '役牌（白）'),
('Yakuhai (hatsu)', '役牌（発）'),
('Honitsu', '混一色'),
('Honroutou', '混老頭'),
('Houtei Raoyui', '河底撈魚'),
('Iipeiko', '一盃口'),
('Ippatsu', '一発'),
('Ittsu', '一気通貫'),
('Junchan', '純全帯幺九'),
('Nagashi Mangan', '流し満貫'),
('Yakuhai (north)', '役牌（北）'),
('Open Riichi', 'オープン立直'),
('Pinfu', '平和'),
('Renhou', '人和'),
('Riichi', '立直'),
('Rinshan Kaihou', '嶺上開花'),
('Ryanpeikou', '二盃口'),
('San Ankou', '三暗刻'),
('San Kantsu', '三槓子'),
('Sanshoku Doujun', '三色同順'),
('Sanshoku Doukou', '三色同刻'),
('Shou Sangen', '小三元'),
('Yakuhai (south)', '役牌（南）'),
('Tanyao', '断么九'),
('Toitoi', '対々和'),
('Menzen Tsumo', '門前清自摸和'),
('Yakuhai (west)', '役牌（西）'),
('Yakuhai (wind of place)', '役牌（自風）'),
('Yakuhai (wind of round)', '役牌（場風）'),
('Daisangen', '大三元'),
('Chinroutou', '清老頭'),
('Suu Kantsu', '四槓子'),
('Chuuren Poutou', '九蓮宝燈'),
('Suu Ankou', '四暗刻'),
('Dai Suushii', '大四喜'),
('Suu Ankou Tanki', '四暗刻単騎待ち'),
('Sashikomi', '差し込み'),
('Tsuu Iisou', '字一色'),
('Kokushi Musou', '国士無双'),
('Shousuushii', '小四喜'),
('Kokushi Musou Juusanmen Matchi', '国士無双十三面待ち'),
('Ryuuiisou', '緑一色'),
('Renhou (yakuman)', '人和（役満）'),
('Tenhou', '天和'),
('Daisharin', '大車輪'),
('Daisuurin', '大数隣'),
('Daichikurin', '大竹林'),
('Daichisei', '大七星'),
('Daburu Chuuren Poutou', 'ダブル九蓮宝燈'),
('Paarenchan', '八連荘'),
('Chiihou', '地和');
